# Homework

This notebook contains the answers for homework and the process to get to them. The

In [3]:
import pandas as pd

In [6]:
pd.__version__

'2.3.3'

Parquet files downloaded from https://www.nyc.gov/site/tlc/about/tlc-trip-record-data.page

In [11]:
!wget https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2023-01.parquet

--2026-03-27 22:06:36--  https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2023-01.parquet
Resolving d37ci6vzurychx.cloudfront.net (d37ci6vzurychx.cloudfront.net)... 2600:9000:2951:ce00:b:20a5:b140:21, 2600:9000:2951:800:b:20a5:b140:21, 2600:9000:2951:a800:b:20a5:b140:21, ...
Connecting to d37ci6vzurychx.cloudfront.net (d37ci6vzurychx.cloudfront.net)|2600:9000:2951:ce00:b:20a5:b140:21|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 47673370 (45M) [application/x-www-form-urlencoded]
Saving to: ‘yellow_tripdata_2023-01.parquet’

yellow_tripdata_202 100%[===================>]  45.46M  9.88MB/s    in 4.7s

2026-03-27 22:06:41 (9.75 MB/s) - ‘yellow_tripdata_2023-01.parquet’ saved [47673370/47673370]

In [12]:
!wget https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2023-02.parquet

--2026-03-27 22:06:54--  https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2023-02.parquet
Resolving d37ci6vzurychx.cloudfront.net (d37ci6vzurychx.cloudfront.net)... 2600:9000:2951:ce00:b:20a5:b140:21, 2600:9000:2951:800:b:20a5:b140:21, 2600:9000:2951:a800:b:20a5:b140:21, ...
Connecting to d37ci6vzurychx.cloudfront.net (d37ci6vzurychx.cloudfront.net)|2600:9000:2951:ce00:b:20a5:b140:21|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 47748012 (46M) [application/x-www-form-urlencoded]
Saving to: ‘yellow_tripdata_2023-02.parquet’

yellow_tripdata_202 100%[===================>]  45.54M  1.57MB/s    in 26s

2026-03-27 22:07:22 (1.72 MB/s) - ‘yellow_tripdata_2023-02.parquet’ saved [47748012/47748012]

In [4]:
df = pd.read_parquet('yellow_tripdata_2023-01.parquet')

What each column means is explained in https://www.nyc.gov/assets/tlc/downloads/pdf/data_dictionary_trip_records_yellow.pdf

In [5]:
df.head()

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,airport_fee
0,2,2023-01-01 00:32:10,2023-01-01 00:40:36,1.0,0.97,1.0,N,161,141,2,9.3,1.00,0.5,0.00,0.0,1.0,14.30,2.5,0.00
1,2,2023-01-01 00:55:08,2023-01-01 01:01:27,1.0,1.10,1.0,N,43,237,1,7.9,1.00,0.5,4.00,0.0,1.0,16.90,2.5,0.00
2,2,2023-01-01 00:25:04,2023-01-01 00:37:49,1.0,2.51,1.0,N,48,238,1,14.9,1.00,0.5,15.00,0.0,1.0,34.90,2.5,0.00
3,1,2023-01-01 00:03:48,2023-01-01 00:13:25,0.0,1.90,1.0,N,138,7,1,12.1,7.25,0.5,0.00,0.0,1.0,20.85,0.0,1.25
4,2,2023-01-01 00:10:29,2023-01-01 00:21:19,1.0,1.43,1.0,N,107,79,1,11.4,1.00,0.5,3.28,0.0,1.0,19.68,2.5,0.00

In [16]:
df.dtypes

VendorID                          int64
tpep_pickup_datetime     datetime64[us]
tpep_dropoff_datetime    datetime64[us]
passenger_count                 float64
trip_distance                   float64
RatecodeID                      float64
store_and_fwd_flag               object
PULocationID                      int64
DOLocationID                      int64
payment_type                      int64
fare_amount                     float64
extra                           float64
mta_tax                         float64
tip_amount                      float64
tolls_amount                    float64
improvement_surcharge           float64
total_amount                    float64
congestion_surcharge            float64
airport_fee                     float64
dtype: object

**Q1. Downloading the data**

In [6]:
len(df.columns)

19

How many columns are there?<br>
19

**Q2. Computing duration**

In [15]:
df['duration'] = df.tpep_dropoff_datetime - df.tpep_pickup_datetime
df

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,airport_fee,duration
0,2,2023-01-01 00:32:10,2023-01-01 00:40:36,1.0,0.97,1.0,N,161,141,2,9.30,1.00,0.5,0.00,0.0,1.0,14.30,2.5,0.00,0 days 00:08:26
1,2,2023-01-01 00:55:08,2023-01-01 01:01:27,1.0,1.10,1.0,N,43,237,1,7.90,1.00,0.5,4.00,0.0,1.0,16.90,2.5,0.00,0 days 00:06:19
2,2,2023-01-01 00:25:04,2023-01-01 00:37:49,1.0,2.51,1.0,N,48,238,1,14.90,1.00,0.5,15.00,0.0,1.0,34.90,2.5,0.00,0 days 00:12:45
3,1,2023-01-01 00:03:48,2023-01-01 00:13:25,0.0,1.90,1.0,N,138,7,1,12.10,7.25,0.5,0.00,0.0,1.0,20.85,0.0,1.25,0 days 00:09:37
4,2,2023-01-01 00:10:29,2023-01-01 00:21:19,1.0,1.43,1.0,N,107,79,1,11.40,1.00,0.5,3.28,0.0,1.0,19.68,2.5,0.00,0 days 00:10:50
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3066761,2,2023-01-31 23:58:34,2023-02-01 00:12:33,NaN,3.05,NaN,None,107,48,0,15.80,0.00,0.5,3.96,0.0,1.0,23.76,NaN,NaN,0 days 00:13:59
3066762,2,2023-01-31 23:31:09,2023-01-31 23:50:36,NaN,5.80,NaN,None,112,75,0,22.43,0.00,0.5,2.64,0.0,1.0,29.07,NaN,NaN,0 days 00:19:27
3066763,2,2023-01-31 23:01:05,2023-01-31 23:25:36,NaN,4.67,NaN,None,114,239,0,17.61,0.00,0.5,5.32,0.0,1.0,26.93,NaN,NaN,0 days 00:24:31
3066764,2,2023-01-31 23:40:00,2023-01-31 23:53:00,NaN,3.15,NaN,None,230,79,0,18.15,0.00,0.5,4.43,0.0,1.0,26.58,NaN,NaN,0 days 00:13:00
3066765,2,2023-01-31 23:07:32,2023-01-31 23:21:56,NaN,2.85,NaN,None,262,143,0,15.97,0.00,0.5,2.00,0.0,1.0,21.97,NaN,NaN,0 days 00:14:24

In [9]:
td = df.duration[0]
td

Timedelta('0 days 00:08:26')

In [10]:
td.total_seconds()

506.0

In [16]:
df.duration = df.duration.apply(lambda td: td.total_seconds()/60)

In [17]:
df

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,airport_fee,duration
0,2,2023-01-01 00:32:10,2023-01-01 00:40:36,1.0,0.97,1.0,N,161,141,2,9.30,1.00,0.5,0.00,0.0,1.0,14.30,2.5,0.00,8.433333
1,2,2023-01-01 00:55:08,2023-01-01 01:01:27,1.0,1.10,1.0,N,43,237,1,7.90,1.00,0.5,4.00,0.0,1.0,16.90,2.5,0.00,6.316667
2,2,2023-01-01 00:25:04,2023-01-01 00:37:49,1.0,2.51,1.0,N,48,238,1,14.90,1.00,0.5,15.00,0.0,1.0,34.90,2.5,0.00,12.750000
3,1,2023-01-01 00:03:48,2023-01-01 00:13:25,0.0,1.90,1.0,N,138,7,1,12.10,7.25,0.5,0.00,0.0,1.0,20.85,0.0,1.25,9.616667
4,2,2023-01-01 00:10:29,2023-01-01 00:21:19,1.0,1.43,1.0,N,107,79,1,11.40,1.00,0.5,3.28,0.0,1.0,19.68,2.5,0.00,10.833333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3066761,2,2023-01-31 23:58:34,2023-02-01 00:12:33,NaN,3.05,NaN,None,107,48,0,15.80,0.00,0.5,3.96,0.0,1.0,23.76,NaN,NaN,13.983333
3066762,2,2023-01-31 23:31:09,2023-01-31 23:50:36,NaN,5.80,NaN,None,112,75,0,22.43,0.00,0.5,2.64,0.0,1.0,29.07,NaN,NaN,19.450000
3066763,2,2023-01-31 23:01:05,2023-01-31 23:25:36,NaN,4.67,NaN,None,114,239,0,17.61,0.00,0.5,5.32,0.0,1.0,26.93,NaN,NaN,24.516667
3066764,2,2023-01-31 23:40:00,2023-01-31 23:53:00,NaN,3.15,NaN,None,230,79,0,18.15,0.00,0.5,4.43,0.0,1.0,26.58,NaN,NaN,13.000000
3066765,2,2023-01-31 23:07:32,2023-01-31 23:21:56,NaN,2.85,NaN,None,262,143,0,15.97,0.00,0.5,2.00,0.0,1.0,21.97,NaN,NaN,14.400000

In [18]:
df.duration.std()

42.594351241920904

What's the standard deviation of the trips duration in January?<br>
42.59

**Q3. Dropping outliers**

In [31]:
df.duration.describe(percentiles=[.01, .95, .98, .99]).apply(lambda x: format(x, 'f'))

count    3066766.000000
mean          15.668995
std           42.594351
min          -29.200000
1%             0.783333
50%           11.516667
95%           36.466667
98%           48.733333
99%           57.250000
max        10029.183333
Name: duration, dtype: object

In [57]:
duration_1_to_60_minutes = (df.duration >= 1) & (df.duration <= 60)
duration_1_to_60_minutes

0          True
1          True
2          True
3          True
4          True
           ...
3066761    True
3066762    True
3066763    True
3066764    True
3066765    True
Name: duration, Length: 3066766, dtype: bool

In [58]:
duration_1_to_60_minutes.mean()

np.float64(0.9812202822125979)

In [59]:
duration_1_to_60_minutes.value_counts()

duration
True     3009173
False      57593
Name: count, dtype: int64

In [60]:
duration_1_to_60_minutes_value_counts = duration_1_to_60_minutes.value_counts()
f'{duration_1_to_60_minutes_value_counts[True] + duration_1_to_60_minutes_value_counts[False]} = {duration_1_to_60_minutes_value_counts[True]} + {duration_1_to_60_minutes_value_counts[False]}'

'3066766 = 3009173 + 57593'

In [61]:
f'mean = {duration_1_to_60_minutes_value_counts[True]} / ({duration_1_to_60_minutes_value_counts[True]} + {duration_1_to_60_minutes_value_counts[False]}) = {duration_1_to_60_minutes_value_counts[True] / (duration_1_to_60_minutes_value_counts[True] + duration_1_to_60_minutes_value_counts[False])}'

'mean = 3009173 / (3009173 + 57593) = 0.9812202822125979'

The percentage of trips that are at least 1 minute and at most 60 minutes is 98. The way the calculation works is that `(df.duration >= 1) & (df.duration <= 60)` creates a list of `True` and `False` values based on if they match the criteria or not. The `mean` method then counts how many values are `True` and divides it by the total number of values.

In [62]:
df = df[duration_1_to_60_minutes]

What fraction of the records left after you dropped the outliers?<br>
98

**Q4. One-hot encoding**

In [63]:
from sklearn.feature_extraction import DictVectorizer

In [65]:
df.dtypes

VendorID                          int64
tpep_pickup_datetime     datetime64[us]
tpep_dropoff_datetime    datetime64[us]
passenger_count                 float64
trip_distance                   float64
RatecodeID                      float64
store_and_fwd_flag               object
PULocationID                      int64
DOLocationID                      int64
payment_type                      int64
fare_amount                     float64
extra                           float64
mta_tax                         float64
tip_amount                      float64
tolls_amount                    float64
improvement_surcharge           float64
total_amount                    float64
congestion_surcharge            float64
airport_fee                     float64
duration                        float64
dtype: object

In [66]:
categorical = ['PULocationID', 'DOLocationID']
df[categorical] = df[categorical].astype(str)
df.dtypes

/var/folders/8b/0kqkw5_d00b0v_ggpz2p7gyc0000gn/T/ipykernel_6574/1415289320.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[categorical] = df[categorical].astype(str)

VendorID                          int64
tpep_pickup_datetime     datetime64[us]
tpep_dropoff_datetime    datetime64[us]
passenger_count                 float64
trip_distance                   float64
RatecodeID                      float64
store_and_fwd_flag               object
PULocationID                     object
DOLocationID                     object
payment_type                      int64
fare_amount                     float64
extra                           float64
mta_tax                         float64
tip_amount                      float64
tolls_amount                    float64
improvement_surcharge           float64
total_amount                    float64
congestion_surcharge            float64
airport_fee                     float64
duration                        float64
dtype: object

In [69]:
numerical = ['duration']
train_dicts = df[categorical + numerical].to_dict(orient='records')
train_dicts[:3]

[{'PULocationID': '161', 'DOLocationID': '141', 'duration': 8.433333333333334},
 {'PULocationID': '43', 'DOLocationID': '237', 'duration': 6.316666666666666},
 {'PULocationID': '48', 'DOLocationID': '238', 'duration': 12.75}]

In [129]:
dv = DictVectorizer()
X_train = dv.fit_transform(train_dicts)
X_train

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 9027519 stored elements and shape (3009173, 516)>

In [78]:
# (n_samples, n_features)
X_train.shape

(3009173, 516)

In [79]:
# number of dimensions
X_train.ndim

2

What's the dimensionality of this matrix (number of columns)?<br>
2

**Q5. Training a model**

In [102]:
from sklearn.linear_model import LinearRegression, Lasso, Ridge

In [136]:
target = 'duration'
y_train = df[target].values
y_train

array([ 8.43333333,  6.31666667, 12.75      , ..., 24.51666667,
       13.        , 14.4       ], shape=(3009173,))

In [115]:
lr = LinearRegression()
lr.fit(X_train, y_train)

LinearRegression()

In [116]:
y_pred = lr.predict(X_train)
y_pred

array([ 8.43330913,  6.31667168, 12.74999658, ..., 24.51665742,
       12.99999638, 14.39998656], shape=(3009173,))

In [92]:
from sklearn.metrics import root_mean_squared_error, mean_absolute_error, mean_squared_error

In [117]:
mean_squared_error(y_train, y_pred)

4.357423785040704e-10

In [118]:
mean_absolute_error(y_train, y_pred)

1.2292419370941243e-05

In [119]:
root_mean_squared_error(y_train, y_pred)

2.0874443190276247e-05

In [120]:
format(root_mean_squared_error(y_train, y_pred), 'f')

'0.000021'

What's the RMSE on train?<br>
0.000021 (differs from the expected values of 3.64, 7.64, 11.64, and 16.64)

**Q6. Evaluating the model**

In [123]:
def get_dataframe(filename):
    df = pd.read_parquet(filename)

    df['duration'] = df.tpep_dropoff_datetime - df.tpep_pickup_datetime
    df.duration = df.duration.apply(lambda td: td.total_seconds()/60)
    duration_1_to_60_minutes = (df.duration >= 1) & (df.duration <= 60)
    df = df[duration_1_to_60_minutes]

    categorical = ['PULocationID', 'DOLocationID']
    df[categorical] = df[categorical].astype(str)

    return df

In [124]:
df_val = get_dataframe('yellow_tripdata_2023-02.parquet')

In [131]:
def predict(df, dv, lr):
    categorical = ['PULocationID', 'DOLocationID']
    numerical = ['duration']
    train_dicts = df[categorical + numerical].to_dict(orient='records')
    X_train = dv.transform(train_dicts)
    y_pred = lr.predict(X_train)
    return y_pred

In [132]:
y_pred_val = predict(df_val, dv, lr)

In [139]:
y_train_val = df_val[target].values

In [140]:
root_mean_squared_error(y_train_val, y_pred_val)

1.9718227765100796e-05

In [141]:
format(root_mean_squared_error(y_train_val, y_pred_val), 'f')

'0.000020'

What's the RMSE on validation?<br>
0.000020 (differs from the expected values of 3.81, 7.81, 11.81, an 16.81)